---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev
      - libxml2-utils
      - intltool

cache:
  directories:
    - /tmp/liftoff

matrix:
  include:
    - env: DIST=juno

before_install:
  - docker pull ubuntu:18.04

install:
  - npm install @elementaryos/houston@1

script:
  - houston ci
    --type system-app
    --name-appstream io.elementary.calendar.desktop
    --name-domain io.elementary.calendar
    --name-human Calendar
    --distribution $DIST
